version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: bitx-kanban
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
